test signature

diff --git a/.github/workflows/build-sign-notarize.yml b/.github/workflows/build-sign-notarize.yml
--- a/.github/workflows/build-sign-notarize.yml
+++ b/.github/workflows/build-sign-notarize.yml
@@ -95,7 +95,7 @@ jobs:
       - name: build release
         run: tea -E xc dist
         env:
-          CSC_IDENTITY_AUTO_DISCOVERY: true
+          CSC_IDENTITY_AUTO_DISCOVERY: false
           SYNC_I18N: 1
           PUBLIC_MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_PROJECT_TOKEN }}
           DEBUG_BUILD: ${{ inputs.debug }}
@@ -133,3 +133,135 @@ jobs:
         env:
           CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
 
+  notarize-mac-installers:
+    needs: [build]
+    runs-on: macos-11
+    outputs:
+      s3-installers-key: ${{ steps.s3-installers-upload.outputs.s3-key }}
+    strategy:
+      matrix:
+        platform:
+          # no need for x86-64
+          - darwin+aarch64
+    steps:
+    - uses: teaxyz/setup@v0
+    - uses: actions/checkout@v3
+    - name: cache node_modules build
+      uses: actions/cache@v3
+      with:
+        key: darwin+x86-64-pnpm
+        path: |
+          ./pnpm
+          ./.pnpm-store
+          ./node_modules
+          ./modules/desktop/node_modules
+          ./modules/ui/node_modules
+    - uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: us-east-1
+
+    - name: s3 artifact download
+      env:
+        S3_KEY: ${{ needs.build.outputs.s3-artifacts-key }}
+      run: aws s3 cp $S3_KEY artifacts.tgz
+
+    # prepare folders
+    - run: mkdir dist
+    - run: tar xzf artifacts.tgz -C dist
+
+    - name: get .zip of arm64 and x86+64
+      id: app_files
+      working-directory: ./dist
+      run: |
+        ARM64_ZIP=$(ls | grep -Ev blockmap | grep arm64-mac.zip)
+        X86_ZIP=$(ls | grep -Ev blockmap | grep -Ev arm64 | grep mac.zip)
+        ARM64_DMG=$(ls | grep -Ev blockmap | grep arm64.dmg)
+        X86_DMG=$(ls | grep -Ev blockmap | grep -Ev arm64 | grep dmg)
+        echo zip_arm64=$ARM64_ZIP >> $GITHUB_OUTPUT
+        echo zip_x86=$X86_ZIP >> $GITHUB_OUTPUT
+        echo dmg_arm64=$ARM64_DMG >> $GITHUB_OUTPUT
+        echo dmg_x86=$X86_DMG >> $GITHUB_OUTPUT
+    # Notarize. Can take up to 10 minutes (and fail) asynchronously
+    # sometimes this might fail because exact the same zip has been uploaded already
+    - name: notarize .app arm64
+      run: xcrun altool --notarize-app --username "$APPLE_ID" --password "$APPLE_PASSWORD" --primary-bundle-id "com.tea.xyz" --file dist/$ZIP_FILE || true
+      env:
+        APPLE_ID: ${{ secrets.APPLE_ID }}
+        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
+        ZIP_FILE: ${{ steps.app_files.outputs.zip_arm64 }}
+
+    - name: notarize .app x86+64
+      run: xcrun altool --notarize-app --username "$APPLE_ID" --password "$APPLE_PASSWORD" --primary-bundle-id "com.tea.xyz" --file dist/$ZIP_FILE || true
+      env:
+        APPLE_ID: ${{ secrets.APPLE_ID }}
+        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
+        ZIP_FILE: ${{ steps.app_files.outputs.zip_x86 }}
+
+    # prepare for DMG creation
+    - name: prepare installer folders
+      run: |
+        mkdir x86_installer && mkdir arm64_installer
+        tar xzf dist/$ZIP_FILE_X86 -C x86_installer/
+        tar xzf dist/$ZIP_FILE_ARM64 -C arm64_installer/
+      env:
+        ZIP_FILE_X86: ${{ steps.app_files.outputs.zip_x86 }}
+        ZIP_FILE_ARM64: ${{ steps.app_files.outputs.zip_arm64 }}
+
+    - name: create x86 dmg
+      run: |
+        tea +github.com/create-dmg/create-dmg create-dmg \
+        --volname "Tea Installer" \
+        --window-pos 200 120 \
+        --window-size 800 400 \
+        --icon-size 100 \
+        --icon "tea.app" 200 190 \
+        --volicon "./modules/desktop/electron/icon.icns" \
+        --hide-extension "tea.app" \
+        --app-drop-link 600 185 \
+        --sandbox-safe \
+        "$filename" \
+        "$installer_folder"
+      env:
+        filename: ${{ steps.app_files.outputs.dmg_x86 }}
+        installer_folder: x86_installer/
+
+    - name: create arm64 dmg
+      run: |
+        tea +github.com/create-dmg/create-dmg create-dmg \
+        --volname "Tea Installer" \
+        --window-pos 200 120 \
+        --window-size 800 400 \
+        --icon-size 100 \
+        --icon "tea.app" 200 190 \
+        --volicon "./modules/desktop/electron/icon.icns" \
+        --hide-extension "tea.app" \
+        --app-drop-link 600 185 \
+        --sandbox-safe \
+        "$filename" \
+        "$installer_folder"
+      env:
+        filename: ${{ steps.app_files.outputs.dmg_arm64 }}
+        installer_folder: arm64_installer/
+
+    # finalize dist artifacts
+    - name: replace old DMG files in dist folder
+      run: |
+        mv $x86dmg dist
+        mv $arm64dmg dist
+        tea -E pnpm install
+        tea -E node .github/create-correct-release-yaml.js ./dist
+        tar -czvf dist.tgz -C dist/ .
+      env:
+        x86dmg: ${{ steps.app_files.outputs.dmg_x86 }}
+        arm64dmg: ${{ steps.app_files.outputs.dmg_arm64 }}
+
+    - name: s3 installers upload
+      id: s3-installers-upload
+      env:
+        prefix: ${{ inputs.s3-prefix }}
+      run: |
+        export S3_INSTALLERS_KEY=s3://preview.gui.tea.xyz/$prefix/dist.tgz
+        aws s3 cp dist.tgz $S3_INSTALLERS_KEY
+        echo s3-key=$S3_INSTALLERS_KEY >> $GITHUB_OUTPUT
