synchronize ci/main

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -120,99 +120,167 @@ jobs:
           #   name: linux+aarch64
     container: ${{ matrix.platform.container }}
     steps:
-      - uses: actions/checkout@v3
+    - uses: actions/checkout@v3
+    - uses: teaxyz/setup@v0
+      if: startsWith(matrix.platform.name, 'darwin')
 
-      - name: build tauri for MacOS
-        # uses: teaxyz/setup@v0
-        if: startsWith(matrix.platform.name, 'darwin')
-        # FROM: https://tauri.app/v1/guides/distribution/sign-macos
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          ENABLE_CODE_SIGNING: ${{ secrets.GUI_APPLE_CERTIFICATE }}
-          APPLE_CERTIFICATE: ${{ secrets.GUI_APPLE_CERTIFICATE }}
-          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.GUI_APPLE_CERTIFICATE_PASSWORD }}
-          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
-          # TODO: uncomment once isolated m1 runner is setup with latest xcode
-          # only used for notarization
-          # APPLE_ID: ${{ secrets.APPLE_ID }}
-          # APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
-        run: |
-          sh <(curl https://tea.xyz) -ES xc build
+    - name: build tauri for MacOS
+      if: startsWith(matrix.platform.name, 'darwin')
+      # FROM: https://tauri.app/v1/guides/distribution/sign-macos
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        ENABLE_CODE_SIGNING: ${{ secrets.GUI_APPLE_CERTIFICATE }}
+        APPLE_CERTIFICATE: ${{ secrets.GUI_APPLE_CERTIFICATE }}
+        APPLE_CERTIFICATE_PASSWORD: ${{ secrets.GUI_APPLE_CERTIFICATE_PASSWORD }}
+        APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
+      run: tea -ES xc build
 
-      - name: build tauri for Linux
-        # uses: teaxyz/setup@v0
-        if: startsWith(matrix.platform.name, 'linux')
-        # TODO: https://tauri.app/v1/guides/distribution/sign-linux
-        uses: docker://getneil/tea-builder:latest
-      
-      - name: build platform output
-        id: build_platform
-        env:
-          platform: ${{ matrix.platform.name }}
-        run: |
-          EXTENSION=dmg
-          BUILD_PLATFORM=$(echo $platform | sed -e "s/darwin+//g" | sed -e "s/linux+//g")
-          [[ $BUILD_PLATFORM = "x86-64" ]] && BUILD_PLATFORM="x64" || BUILD_PLATFORM=$BUILD_PLATFORM
-          [[ $platform = "linux+x86-64" ]] && BUILD_PLATFORM="amd64" || BUILD_PLATFORM=$BUILD_PLATFORM
-          [[ $platform = "linux+x86-64" ]] && EXTENSION="deb"
-          echo "build_platform=$BUILD_PLATFORM" >> $GITHUB_OUTPUT
-          echo "extension=$EXTENSION" >> $GITHUB_OUTPUT
+    - name: build tauri for Linux
+      if: startsWith(matrix.platform.name, 'linux')
+      # TODO: https://tauri.app/v1/guides/distribution/sign-linux
+      uses: docker://getneil/tea-builder:latest
 
-      - name: zip .app for MacOS
-        if: matrix.platform.name == 'darwin+x86-64' || matrix.platform.name == 'darwin+aarch64'
-        run: |
-          cd ./modules/gui/src-tauri/target/release/bundle/macos/ && zip -r tea.zip tea.app
+    - run: >
+        tar -czvf artifacts.tgz
+          -C ./modules/gui/src-tauri/target/release/bundle .
 
-      - uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+    - name: upload artifacts
+      uses: actions/upload-artifact@v3
+      with:
+        name: ${{ matrix.platform.name }}
+        path: artifacts.tgz
+        if-no-files-found: error
 
-      - name: cp package images from prod to preview bucket
-        env:
-          prefix: ${{ needs.changes.outputs.preview_folder }}
-          platform: ${{ steps.build_platform.outputs.build_platform }}
-          extension: ${{ steps.build_platform.outputs.extension }}
-        run: |
-          aws s3 cp "./modules/gui/src-tauri/target/release/bundle/$extension/tea_0.1.0_$platform.$extension" \
-            "s3://preview.gui.tea.xyz/$prefix/tea_$platform.$extension"
-  
-      - name: cp package zip for MacOS
-        if: matrix.platform.name == 'darwin+x86-64' || matrix.platform.name == 'darwin+aarch64'
-        env:
-          prefix: ${{ needs.changes.outputs.preview_folder }}
-          platform: ${{ steps.build_platform.outputs.build_platform }}
-        run: |
-          aws s3 cp ./modules/gui/src-tauri/target/release/bundle/macos/tea.zip "s3://preview.gui.tea.xyz/$prefix/tea_$platform.zip"
+  notorize_tauri:
+    needs: [build_tauri]
+    runs-on: macos-11
+    strategy:
+      matrix:
+        platform:
+          - darwin+x86-64
+          - darwin+aarch64
+    steps:
+    - uses: actions/download-artifact@v3
+      with:
+        name: ${{ matrix.platform }}
 
-      - name: comment install for Linux
-        if: startsWith(matrix.platform.name, 'linux')
-        uses: mshick/add-pr-comment@v2
-        with:
-          message-id: ${{ matrix.platform.id }}-comment
-          message: |
-            **installer for Linux ${{ matrix.platform.name }} is at**: 
-            <a href="http://preview.gui.tea.xyz.s3-website-us-east-1.amazonaws.com/${{ needs.changes.outputs.preview_folder }}/tea_${{steps.build_platform.outputs.build_platform}}.${{steps.build_platform.outputs.extension}}" target="_blank">here</a>
+    - run: tar xzf artifacts.tgz
 
-            ```bash
-            http://preview.gui.tea.xyz.s3-website-us-east-1.amazonaws.com/${{ needs.changes.outputs.preview_folder }}/tea_${{ steps.build_platform.outputs.build_platform }}.${{ steps.build_platform.outputs.extension }}
-            ```
-            copy-paste into a browser to download
+    - run: cd ./macos/ && zip -r tea.zip tea.app
 
-      - name: comment install for MacOS
-        if: startsWith(matrix.platform.name, 'darwin')
-        uses: mshick/add-pr-comment@v2
-        with:
-          message-id: ${{ matrix.platform.id }}-comment
-          message: |
-            **installers for MacOS ${{ matrix.platform.name }} is at**: 
-            <a href="http://preview.gui.tea.xyz.s3-website-us-east-1.amazonaws.com/${{ needs.changes.outputs.preview_folder }}/tea_${{steps.build_platform.outputs.build_platform}}.zip" target="_blank">.zip</a>
-            or
-            <a href="http://preview.gui.tea.xyz.s3-website-us-east-1.amazonaws.com/${{ needs.changes.outputs.preview_folder }}/tea_${{steps.build_platform.outputs.build_platform}}.dmg" target="_blank">.dmg</a>
+    # Notarize. Can take up to 10 minutes (and fail) asynchronously
+    - run: xcrun altool --notarize-app --username "$APPLE_ID" --password "$APPLE_PASSWORD" --primary-bundle-id "com.tea.xyz" --file ./macos/tea.zip
+      env:
+        APPLE_ID: ${{ secrets.APPLE_ID }}
+        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
 
-            ```bash
-            http://preview.gui.tea.xyz.s3-website-us-east-1.amazonaws.com/${{ needs.changes.outputs.preview_folder }}/tea_${{ steps.build_platform.outputs.build_platform }}.zip
-            http://preview.gui.tea.xyz.s3-website-us-east-1.amazonaws.com/${{ needs.changes.outputs.preview_folder }}/tea_${{ steps.build_platform.outputs.build_platform }}.dmg
-            ```
-            copy-paste into a browser to download
+  upload:
+    needs: [build_tauri, notorize_tauri]
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        platform:
+          - darwin+x86-64
+          - linux+x86-64
+          - darwin+aarch64
+          # - linux+aarch64
+    steps:
+    - uses: actions/download-artifact@v3
+      with:
+        name: ${{ matrix.platform }}
+
+    - run: tar xzf artifacts.tgz
+
+    - name: build platform output
+      id: build_platform
+      env:
+        platform: ${{ matrix.platform }}
+      run: |
+        BUILD_PLATFORM=$(echo $platform | sed -e "s/darwin+//g" | sed -e "s/linux+//g")
+        EXTENSION=dmg
+        case $platform in
+          "linux+x86-64")
+            BUILD_PLATFORM="amd64"
+            EXTENSION="deb"
+            ;;
+          "linux+aarch64")
+            BUILD_PLATFORM="aarch64"
+            EXTENSION="deb"
+            ;;
+          "darwin+aarch64")
+            BUILD_PLATFORM="aarch64"
+            EXTENSION="dmg"
+            ;;
+          "darwin+x86-64")
+            BUILD_PLATFORM="x64"
+            EXTENSION="dmg"
+            ;;
+          *)
+            echo "Unknown platform $platform"
+            exit 1
+            ;;
+        esac
+        echo "build_platform=$BUILD_PLATFORM" >> $GITHUB_OUTPUT
+        echo "extension=$EXTENSION" >> $GITHUB_OUTPUT
+
+    - name: zip .app for MacOS
+      if: startsWith(matrix.platform, 'darwin+')
+      run: |
+        cd ./modules/gui/src-tauri/target/release/bundle/macos/
+        zip -r tea.zip tea.app
+
+    - uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: us-east-1
+
+    - name: cp package images from prod to preview bucket
+      env:
+        prefix: ${{ needs.changes.outputs.preview_folder }}
+        platform: ${{ steps.build_platform.outputs.build_platform }}
+        extension: ${{ steps.build_platform.outputs.extension }}
+      run: >
+        aws s3 cp
+          "./modules/gui/src-tauri/target/release/bundle/$extension/tea_0.1.0_$platform.$extension"
+          "s3://preview.gui.tea.xyz/$prefix/tea_$platform.$extension"
+
+    - name: cp package zip for MacOS
+      if: matrix.platform.name == 'darwin+x86-64' || matrix.platform.name == 'darwin+aarch64'
+      env:
+        prefix: ${{ needs.changes.outputs.preview_folder }}
+        platform: ${{ steps.build_platform.outputs.build_platform }}
+      run: >
+        aws s3 cp
+          ./modules/gui/src-tauri/target/release/bundle/macos/tea.zip "s3://preview.gui.tea.xyz/$prefix/tea_$platform.zip"
+
+    - name: comment install for Linux
+      if: startsWith(matrix.platform.name, 'linux')
+      uses: mshick/add-pr-comment@v2
+      with:
+        message-id: ${{ matrix.platform.id }}-comment
+        message: |
+          **installer for Linux ${{ matrix.platform.name }} is at**:
+          <a href="http://preview.gui.tea.xyz.s3-website-us-east-1.amazonaws.com/${{ needs.changes.outputs.preview_folder }}/tea_${{steps.build_platform.outputs.build_platform}}.${{steps.build_platform.outputs.extension}}" target="_blank">here</a>
+
+          ```bash
+          http://preview.gui.tea.xyz.s3-website-us-east-1.amazonaws.com/${{ needs.changes.outputs.preview_folder }}/tea_${{ steps.build_platform.outputs.build_platform }}.${{ steps.build_platform.outputs.extension }}
+          ```
+          copy-paste into a browser to download
+
+    - name: comment install for MacOS
+      if: startsWith(matrix.platform.name, 'darwin')
+      uses: mshick/add-pr-comment@v2
+      with:
+        message-id: ${{ matrix.platform.id }}-comment
+        message: |
+          **installers for MacOS ${{ matrix.platform.name }} is at**:
+          <a href="http://preview.gui.tea.xyz.s3-website-us-east-1.amazonaws.com/${{ needs.changes.outputs.preview_folder }}/tea_${{steps.build_platform.outputs.build_platform}}.zip" target="_blank">.zip</a>
+          or
+          <a href="http://preview.gui.tea.xyz.s3-website-us-east-1.amazonaws.com/${{ needs.changes.outputs.preview_folder }}/tea_${{steps.build_platform.outputs.build_platform}}.dmg" target="_blank">.dmg</a>
+
+          ```bash
+          http://preview.gui.tea.xyz.s3-website-us-east-1.amazonaws.com/${{ needs.changes.outputs.preview_folder }}/tea_${{ steps.build_platform.outputs.build_platform }}.zip
+          http://preview.gui.tea.xyz.s3-website-us-east-1.amazonaws.com/${{ needs.changes.outputs.preview_folder }}/tea_${{ steps.build_platform.outputs.build_platform }}.dmg
+          ```
+          copy-paste into a browser to download
